### ISSUE TITLE
Umbraco 13.2.0. Error with empty RTEs

### ISSUE THREAD

**Issue by AlexanderWagner82** [rickbutterfield/Our.Umbraco.BlockPreview#48]
I get this error with Umbraco.Community.BlockPreview 1.8.1 and Umbraco.CMS 13.2.0 on empty RTE-properties. 

It works just fine with Umbraco.Community.BlockPreview 1.8.0 and Umbraco.CMS 13.1.0

System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Community.BlockPreview.Services.BackOfficeListPreviewService.GetMarkupForBlock(IPublishedContent page, BlockValue blockValue, String blockEditorAlias, ControllerContext controllerContext, String culture)
   at Umbraco.Community.BlockPreview.Controllers.BlockPreviewApiController.PreviewMarkup(BlockValue data, Int32 pageId, String blockEditorAlias, Boolean isGrid, String culture)

![image](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/assets/7590126/0e70e5ee-5cb1-4037-87c2-b862081f75d8)

**Comment by rickbutterfield** [comment]
You've found a real edge case here! I've also managed to replicate the error in 13.1.1, so it's a bug in BlockPreview. Look out for v1.8.2 coming later on today

**Comment by AlexanderWagner82** [comment]
Awesome! Thank you very much :)

**Comment by rickbutterfield** [comment]
@AlexanderWagner82 should be fixed in v1.8.2 if you could please check and confirm? It worked in my test case

**Comment by AlexanderWagner82** [comment]
I've tested with Umbraco 13.2.0 and BlockPreview 1.8.2 and it works like a charm now. 

Thank you for a fast reply and fix!
